# This file is part of Bromite.

# Bromite is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Bromite is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Bromite. If not, see <https://www.gnu.org/licenses/>.

# for placeholder.txt:
#
# this file is intentionally empty
#

cpp_bromite_include("chrome_browser_about_flags_cc") {
  inputs = [ "//cromite_flags/chrome/browser/about_flags_cc/placeholder.txt" ]
  output_file = "chrome_browser_about_flags_cc.inc"
}

cpp_bromite_include("chrome_common_chrome_features_cc") {
  inputs = [ "//cromite_flags/chrome/common/chrome_features_cc/placeholder.txt" ]
  output_file = "chrome_common_chrome_features_cc.inc"
}

cpp_bromite_include("content_common_features_cc") {
  inputs = [ "//cromite_flags/content/common/features_cc/placeholder.txt" ]
  output_file = "content_common_features_cc.inc"
}

cpp_bromite_include("content_public_common_content_features_h") {
  inputs = [ "//cromite_flags/content/public/common/content_features_h/placeholder.txt" ]
  output_file = "content_public_common_content_features_h.inc"
}

cpp_bromite_include("content_public_common_content_features_cc") {
  inputs = [ "//cromite_flags/content/public/common/content_features_cc/placeholder.txt" ]
  output_file = "content_public_common_content_features_cc.inc"
}

cpp_bromite_include("third_party_blink_common_features_cc") {
  inputs = [ "//cromite_flags/third_party/blink/common/features_cc/placeholder.txt" ]
  output_file = "third_party_blink_common_features_cc.inc"
}

cpp_bromite_include("third_party_blink_common_features_h") {
  inputs = [ "//cromite_flags/third_party/blink/common/features_h/placeholder.txt" ]
  output_file = "third_party_blink_common_features_h.inc"
}

cpp_bromite_include("chrome_browser_flags_android_chrome_feature_list_cc") {
  inputs = [ "//cromite_flags/chrome/browser/flags/android/chrome_feature_list_cc/placeholder.txt" ]
  output_file = "chrome_browser_flags_android_chrome_feature_list_cc.inc"
}

cpp_bromite_include("chrome_browser_flags_android_chrome_feature_list_h") {
  inputs = [ "//cromite_flags/chrome/browser/flags/android/chrome_feature_list_h/placeholder.txt" ]
  output_file = "chrome_browser_flags_android_chrome_feature_list_h.inc"
}

cpp_bromite_include("chrome_browser_browser_features_cc") {
  inputs = [ "//cromite_flags/chrome/browser/browser_features_cc/placeholder.txt" ]
  output_file = "chrome_browser_browser_features_cc.inc"
}

cpp_bromite_include("chrome_browser_browser_features_h") {
  inputs = [ "//cromite_flags/chrome/browser/browser_features_h/placeholder.txt" ]
  output_file = "chrome_browser_browser_features_h.inc"
}

cpp_bromite_include("chrome_browser_ui_ui_features_cc") {
  inputs = [ "//cromite_flags/chrome/browser/ui/ui_features_cc/placeholder.txt" ]
  output_file = "chrome_browser_ui_ui_features_cc.inc"
}

cpp_bromite_include("media_base_media_switches_cc") {
  inputs = [ "//cromite_flags/media/base/media_switches_cc/placeholder.txt" ]
  output_file = "media_base_media_switches_cc.inc"
}

cpp_bromite_include("media_base_media_switches_h") {
  inputs = [ "//cromite_flags/media/base/media_switches_h/placeholder.txt" ]
  output_file = "media_base_media_switches_h.inc"
}

cpp_bromite_include("components_content_settings_core_common_features_cc") {
  inputs = [ "//cromite_flags/components/content_settings/core/common/features_cc/placeholder.txt" ]
  output_file = "components_content_settings_core_common_features_cc.inc"
}

cpp_bromite_include("components_permissions_features_cc") {
  inputs = [ "//cromite_flags/components/permissions/features_cc/placeholder.txt" ]
  output_file = "components_permissions_features_cc.inc"
}

cpp_bromite_include("components_offline_pages_core_offline_page_feature_cc") {
  inputs = [ "//cromite_flags/components/offline_pages/core/offline_page_feature_cc/placeholder.txt" ]
  output_file = "components_offline_pages_core_offline_page_feature_cc.inc"
}

cpp_bromite_include("components_offline_pages_core_offline_page_feature_h") {
  inputs = [ "//cromite_flags/components/offline_pages/core/offline_page_feature_h/placeholder.txt" ]
  output_file = "components_offline_pages_core_offline_page_feature_h.inc"
}

cpp_bromite_include("net_base_features_cc") {
  inputs = [ "//cromite_flags/net/base/features_cc/placeholder.txt" ]
  output_file = "net_base_features_cc.inc"
}

cpp_bromite_include("net_base_features_h") {
  inputs = [ "//cromite_flags/net/base/features_h/placeholder.txt" ]
  output_file = "net_base_features_h.inc"
}

cpp_bromite_include("services_network_public_cpp_features_cc") {
  inputs = [ "//cromite_flags/services/network/public/cpp/features_cc/placeholder.txt" ]
  output_file = "services_network_public_cpp_features_cc.inc"
}

cpp_bromite_include("services_network_public_cpp_features_h") {
  inputs = [ "//cromite_flags/services/network/public/cpp/features_h/placeholder.txt" ]
  output_file = "services_network_public_cpp_features_h.inc"
}

cpp_bromite_include("ui_base_features_cc") {
  inputs = [ "//cromite_flags/ui/base/features_cc/placeholder.txt" ]
  output_file = "ui_base_features_cc.inc"
}

cpp_bromite_include("ui_base_features_h") {
  inputs = [ "//cromite_flags/ui/base/features_h/placeholder.txt" ]
  output_file = "ui_base_features_h.inc"
}

cpp_bromite_include("components_password_manager_core_browser_features_password_features_cc") {
  inputs = [ "//cromite_flags/components/password_manager/core/browser/features/password_features_cc/placeholder.txt" ]
  output_file = "components_password_manager_core_browser_features_password_features_cc.inc"
}

component("cromite_flags") {
  deps = [
    ":content_common_features_cc",
    ":content_public_common_content_features_cc",
    ":content_public_common_content_features_h",
    ":components_content_settings_core_common_features_cc",
    ":components_permissions_features_cc",
    ":components_offline_pages_core_offline_page_feature_cc",
    ":components_offline_pages_core_offline_page_feature_h",
    ":components_password_manager_core_browser_features_password_features_cc",
    ":media_base_media_switches_cc",
    ":media_base_media_switches_h",
    ":net_base_features_cc",
    ":net_base_features_h",
    ":chrome_common_chrome_features_cc",
    ":chrome_browser_about_flags_cc",
    ":chrome_browser_flags_android_chrome_feature_list_cc",
    ":chrome_browser_flags_android_chrome_feature_list_h",
    ":chrome_browser_ui_ui_features_cc",
    ":chrome_browser_browser_features_cc",
    ":chrome_browser_browser_features_h",
    ":services_network_public_cpp_features_cc",
    ":services_network_public_cpp_features_h",
    ":third_party_blink_common_features_cc",
    ":third_party_blink_common_features_h",
    ":ui_base_features_cc",
    ":ui_base_features_h",
  ]
}
